language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 1.0.0-preview2-003121


addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1

before_script:
  dotnet restore samples/WebSocketManagerSamples.sln

script:
  dotnet build samples/WebSocketManagerSamples.sln